# AnalyticsExample

use_frameworks!
# platform :ios, '9.3'

pod 'Firebase/Core'
pod 'Firebase/Analytics'

target 'AnalyticsExample' do
end
target 'AnalyticsExampleSwift' do
end
target 'AnalyticsExampleTests' do
end
